name: Build SubUi

run-name: Build SubUi ${{ inputs.version }}

on:
#  push:
#    branches:
#      - "master"
#      - "*test*"
#  pull_request:
#    branches:
#      - "master"
  workflow_dispatch:
    inputs:
      version:
        description: "手动设定版本"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
        # os: [ windows-latest ]
        os: [ubuntu-latest]
        node-version: [ 18.x ]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: corepack enable
        run: corepack enable

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: SubUi
        uses: actions/checkout@v4
        with:
          repository: ZeroRing233/ModSubUiAngularJs
          path: SubUi
          ref: master
          #submodules: recursive

      - name: ModLoader
        uses: actions/checkout@v4
        with:
          repository: Lyoko-Jeremie/sugarcube-2-ModLoader
          path: ModLoader
          ref: master
          submodules: recursive

      - name: init ModLoader
        working-directory: ${{ github.workspace }}/ModLoader
        run: git submodule update --init --recursive

      - name: Build ModLoader
        working-directory: ${{ github.workspace }}/ModLoader
        run: |
          yarn install
          yarn run ts:BeforeSC2
          yarn run webpack:BeforeSC2
          yarn run webpack:BeforeSC2-comp
          yarn run ts:ForSC2
          yarn run webpack:insertTools
          yarn run tras:babel

      - name: Build ModSubUiAngularJs
        working-directory: ${{ github.workspace }}/SubUi/ModSubUiAngularJs
        run: |
          yarn install
          yarn run build:ts
          yarn run build:webpack
          node "${{ github.workspace }}/ModLoader/dist-insertTools/packModZip.js" "boot.json"

      - name: Copy ModSubUiAngularJs
        uses: Lyoko-Jeremie/js-copy-github-action@master
        with:
          srcBase: ${{ github.workspace }}/SubUi/
          source: ModSubUiAngularJs.mod.zip
          destBase: ${{ github.workspace }}/output/
          target: myModSubUi-${{ github.sha }}.zip

      # make package  OK =========================================

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: myModSubUi-${{ github.sha }}
          path: ${{ github.workspace }}/output/myModSubUi-${{ github.sha }}.zip

      - name: Get Current Time
        id: time
        uses: nanzm/get-time-action@master
        with:
          timeZone: UTC+8
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: Rename Archive (Manually)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          mv "output/myModSubUi-${{ github.sha }}.zip" "output/myModSubUi-${{ github.event.inputs.version }}-${{ github.sha }}.zip"

      - name: Archive Release (Releases Manually)
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          files: |
            output/myModSubUi-${{ github.event.inputs.version }}-${{ github.sha }}.zip
          name: Release v${{ github.event.inputs.version }}
          tag_name: v${{ github.event.inputs.version }}-${{ github.sha }}
          body: Release v${{ github.event.inputs.version }}-${{ github.sha }}

      - name: Archive Release (Releases Auto)
        uses: softprops/action-gh-release@v1
        if: ${{ github.event_name != 'workflow_dispatch' }}
        with:
          files: |
            output/myModSubUi-${{ github.sha }}.zip
          name: Auto Release on ${{ steps.time.outputs.time }} (${{ github.sha }})
          tag_name: auto-${{ github.sha }}-${{ steps.time.outputs.time }}
          body: Auto Release on ${{ steps.time.outputs.time }} (${{ github.sha }})
          prerelease: true
